PANDAS

In [3]:
import pandas as pd 
	
df_2 = pd.DataFrame(
   [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

In [7]:
df_2

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [8]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   month              13 non-null     object
 1   avg_high           13 non-null     int64
 2   avg_low            12 non-null     float64
 3   record_high        12 non-null     float64
 4   record_low         13 non-null     int64
 5   avg_precipitation  13 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 752.0+ bytes

In [9]:
df_2.describe()

        avg_high    avg_low  record_high  record_low  avg_precipitation
count  13.000000  12.000000    12.000000   13.000000          13.000000
mean   67.769231  51.000000    91.333333   31.538462           1.296154
std     7.639305   6.060303    12.323911    8.501131           1.115210
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    61.000000  47.250000    82.500000   25.000000           0.170000
50%    67.000000  51.500000    94.000000   30.000000           1.020000
75%    75.000000  56.250000   102.250000   40.000000           2.340000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [10]:
df_2.head()

  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34
3   Apr        67     50.0         92.0          28               1.02
4   May        71     53.0         98.0          35               0.48

In [11]:
df_2.tail()

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [14]:
list(df_2.columns)

['month',
 'avg_high',
 'avg_low',
 'record_high',
 'record_low',
 'avg_precipitation']

In [25]:
df_2.sort_values(['avg_high', 'avg_low'], ascending=[True,False])

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56
1    Feb        61     45.0         78.0          26               3.02
10   Nov        64     48.0         84.0          30               1.70
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
9    Oct        73     54.0         96.0          34               0.81
5    Jun        75     56.0        107.0          41               0.11
7    Aug        77     59.0        102.0          43               0.03
6    Jul        77     58.0        105.0          44               0.00
8    Sep        77     57.0        103.0          40               0.17

In [26]:
df_3 = df_2.sort_values(['avg_high', 'avg_low'], ascending=[True,False])
df_2

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [30]:
df_3

['avg_high']

In [5]:
df = pd.read_csv('LT.csv')
df

,date,home_team,away_team,home_score,away_score,tourniment,city,country
0,1979-07-20,Kyrgyzstan,Lithuania,0,0,Friendly,Moscow,Soviet Union
1,1979-07-22,Georgia,Lithuania,5,0,Friendly,Moscow,Soviet Union
2,1979-07-24,Azerbaijan,Lithuania,0,1,Friendly,Moscow,Soviet Union
3,1979-07-28,Lithuania,Ukraine,0,2,Friendly,Moscow,Soviet Union
4,1979-07-30,Russia,Lithuania,2,0,Friendly,Moscow,Soviet Union
...,...,...,...,...,...,...,...,...
362,2019-09-10,Lithuania,Portugal,1,5,UEFA Euro qualification,Vilnius,Lithuania
363,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine
364,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine
365,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania
366,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania

In [6]:
df.groupby('home_team').sum()

C:\Users\User\AppData\Local\Temp\ipykernel_7520\2691750888.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('home_team').sum()

                        home_score  away_score
home_team
Albania                         10           4
Andorra                          1           3
Argentina                        0           0
Armenia                          8           6
Austria                          6           1
Azerbaijan                       2           2
Belarus                         10           6
Belgium                          1           1
Bosnia and Herzegovina           9           1
Brazil                           3           1
Bulgaria                         3           0
Catalonia                        5           0
Chile                            1           0
Croatia                          2           0
Cyprus                           4           3
Czech Republic                  15           4
Denmark                          4           0
England                         12           0
Estonia                         17          25
Faroe Islands                    3           6
Finland                          3           2
France                           3           0
Georgia                         18           4
Germany                          1           1
Greece                           4           0
Hungary                         14           1
Iceland                          3           0
Israel                           6           3
Italy                            9           1
Kazakhstan                       2           2
Kuwait                           1           0
Kyrgyzstan                       0           0
Latvia                          40          21
Liechtenstein                    4           6
Lithuania                      156         193
Luxembourg                       8           5
Malta                            8           7
Moldova                          9           7
Montenegro                       4           0
North Macedonia                  3           2
Northern Ireland                 2           2
Norway                           3           0
Poland                          19           5
Portugal                         9           2
Republic of Ireland              2           0
Romania                         12           3
Russia                          14           4
San Marino                       0           5
Scotland                        11           3
Serbia                          25           5
Slovakia                        12           4
Slovenia                        11           4
Spain                            9           1
Sweden                           5           2
Switzerland                      8           0
Ukraine                         14           4

In [9]:
df

C:\Users\User\AppData\Local\Temp\ipykernel_7520\1794997511.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[df['away_team'] == 'Lithuania'].groupby("tourniment").sum()

                                 home_score  away_score
tourniment
Baltic Cup                               43          35
Cyprus International Tournament           8           6
FIFA World Cup qualification             80          29
Friendly                                189          67
Malta International Tournament            1           1
UEFA Euro qualification                  73          29
UEFA Nations League                      18           2

In [11]:
list(df.columns)

['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'tourniment',
 'city',
 'country']

In [16]:
def lt_ivarciai(row):
    print(row)
    print('\n\n')

df['Lietuvos_ivarciai'] = df.apply(lt_ivarciai, axis=1)

date                   1979-07-20
home_team              Kyrgyzstan
away_team               Lithuania
home_score                      0
away_score                      0
tourniment               Friendly
city                       Moscow
country              Soviet Union
Lietuvos_ivarciai            None
Name: 0, dtype: object



date                   1979-07-22
home_team                 Georgia
away_team               Lithuania
home_score                      5
away_score                      0
tourniment               Friendly
city                       Moscow
country              Soviet Union
Lietuvos_ivarciai            None
Name: 1, dtype: object



date                   1979-07-24
home_team              Azerbaijan
away_team               Lithuania
home_score                      0
away_score                      1
tourniment               Friendly
city                       Moscow
country              Soviet Union
Lietuvos_ivarciai            None
Name: 2, dtype: object



date                   1979-07-28
home_team               Lithuania
away_team                 Ukraine
home_score                      0
away_score                      2
tourniment               Friendly
city                       Moscow
country              Soviet Union
Lietuvos_ivarciai            None
Name: 3, dtype: object



date                   1979-07-30
home_team                  Russia
away_team               Lithuania
home_score                      2
away_score                      0
tourniment               Friendly
city                       Moscow
country              Soviet Union
Lietuvos_ivarciai            None
Name: 4, dtype: object



date                   1979-08-01
home_team                 Belarus
away_team               Lithuania
home_score                      0
away_score                      2
tourniment               Friendly
city                       Moscow
country              Soviet Union
Lietuvos_ivarciai            None
Name: 5, dtype: object



date                   1979-08-05
home_team                  Russia
away_team               Lithuania
home_score                      2
away_score                      1
tourniment               Friendly
city                       Moscow
country              Soviet Union
Lietuvos_ivarciai            None
Name: 6, dtype: object



date                   1990-05-27
home_team                 Georgia
away_team               Lithuania
home_score                      2
away_score                      2
tourniment               Friendly
city                      Tbilisi
country              Soviet Union
Lietuvos_ivarciai            None
Name: 7, dtype: object



date                 1991-11-15
home_team             Lithuania
away_team               Estonia
home_score                    4
away_score                    1
tourniment           Baltic Cup
city                   Klaipeda
country               Lithuania
Lietuvos_ivarciai          None
Name: 8, dtype: object



date                 1991-11-17
home_team             Lithuania
away_team                Latvia
home_score                    1
away_score                    1
tourniment           Baltic Cup
city                   Kretinga
country               Lithuania
Lietuvos_ivarciai          None
Name: 9, dtype: object



date                 1992-04-14
home_team               Austria
away_team             Lithuania
home_score                    4
away_score                    0
tourniment             Friendly
city                     Vienna
country                 Austria
Lietuvos_ivarciai          None
Name: 10, dtype: object



date                                   1992-04-28
home_team                        Northern Ireland
away_team                               Lithuania
home_score                                      2
away_score                                      2
tourniment           FIFA World Cup qualification
city                                      Belfast
country                          Northern Ireland
Lietuvos_ivarciai                            None
Name: 11, dtype: object



date                 1992-05-20
home_team               Moldova
away_team             Lithuania
home_score                    1
away_score                    1
tourniment             Friendly
city                   Chi?in?u
country                 Moldova
Lietuvos_ivarciai          None
Name: 12, dtype: object



date                                   1992-06-03
home_team                                 Albania
away_team                               Lithuania
home_score                                      1
away_score                                      0
tourniment           FIFA World Cup qualification
city                                       Tirana
country                                   Albania
Lietuvos_ivarciai                            None
Name: 13, dtype: object



date                 1992-07-11
home_team               Estonia
away_team             Lithuania
home_score                    1
away_score                    1
tourniment           Baltic Cup
city                    Liepoja
country                  Latvia
Lietuvos_ivarciai          None
Name: 14, dtype: object



date                 1992-07-12
home_team                Latvia
away_team             Lithuania
home_score                    2
away_score                    3
tourniment           Baltic Cup
city                    Liepoja
country                  Latvia
Lietuvos_ivarciai          None
Name: 15, dtype: object



date                                   1992-08-12
home_team                                  Latvia
away_team                               Lithuania
home_score                                      1
away_score                                      2
tourniment           FIFA World Cup qualification
city                                         Riga
country                                    Latvia
Lietuvos_ivarciai                            None
Name: 16, dtype: object



date                 1992-09-02
home_team             Lithuania
away_team               Georgia
home_score                    1
away_score                    0
tourniment             Friendly
city                     Kaunas
country               Lithuania
Lietuvos_ivarciai          None
Name: 17, dtype: object



date                                   1992-09-23
home_team                               Lithuania
away_team                                 Denmark
home_score                                      0
away_score                                      0
tourniment           FIFA World Cup qualification
city                                      Vilnius
country                                 Lithuania
Lietuvos_ivarciai                            None
Name: 18, dtype: object



date                 1992-10-14
home_team             Lithuania
away_team              Slovakia
home_score                    0
away_score                    1
tourniment             Friendly
city                    Vilnius
country               Lithuania
Lietuvos_ivarciai          None
Name: 19, dtype: object



date                                   1992-10-28
home_team                               Lithuania
away_team                                  Latvia
home_score                                      1
away_score                                      1
tourniment           FIFA World Cup qualification
city                                      Vilnius
country                                 Lithuania
Lietuvos_ivarciai                            None
Name: 20, dtype: object



date                 1993-02-20
home_team                Latvia
away_team             Lithuania
home_score                    1
away_score                    2
tourniment             Friendly
city                     Vantaa
country                 Finland
Lietuvos_ivarciai          None
Name: 21, dtype: object



date                 1993-02-21
home_team               Finland
away_team             Lithuania
home_score                    3
away_score                    0
tourniment             Friendly
city                     Vantaa
country                 Finland
Lietuvos_ivarciai          None
Name: 22, dtype: object



date                                   1993-02-24
home_team                                   Spain
away_team                               Lithuania
home_score                                      5
away_score                                      0
tourniment           FIFA World Cup qualification
city                                      Seville
country                                     Spain
Lietuvos_ivarciai                            None
Name: 23, dtype: object



date                      1993-03-30
home_team                   Slovakia
away_team                  Lithuania
home_score                         2
away_score                         2
tourniment                  Friendly
city                 Dunajsk� Streda
country                     Slovakia
Lietuvos_ivarciai               None
Name: 24, dtype: object



date                 1993-03-31
home_team                Poland
away_team             Lithuania
home_score                    1
away_score                    1
tourniment             Friendly
city                  Brzeszcze
country                  Poland
Lietuvos_ivarciai          None
Name: 25, dtype: object



date                                   1993-04-14
home_team                               Lithuania
away_team                                 Albania
home_score                                      3
away_score                                      1
tourniment           FIFA World Cup qualification
city                                      Vilnius
country                                 Lithuania
Lietuvos_ivarciai                            None
Name: 26, dtype: object



date                 1993-05-18
home_team             Lithuania
away_team               Ukraine
home_score                    1
away_score                    2
tourniment             Friendly
city                    Vilnius
country               Lithuania
Lietuvos_ivarciai          None
Name: 27, dtype: object



date                                   1993-05-25
home_team                               Lithuania
away_team                        Northern Ireland
home_score                                      0
away_score                                      1
tourniment           FIFA World Cup qualification
city                                      Vilnius
country                                 Lithuania
Lietuvos_ivarciai                            None
Name: 28, dtype: object



date                                   1993-06-02
home_team                               Lithuania
away_team                                   Spain
home_score                                      0
away_score                                      2
tourniment           FIFA World Cup qualification
city                                      Vilnius
country                                 Lithuania
Lietuvos_ivarciai                            None
Name: 29, dtype: object



date                                   1993-06-16
home_team                               Lithuania
away_team                     Republic of Ireland
home_score                                      0
away_score                                      1
tourniment           FIFA World Cup qualification
city                                      Vilnius
country                                 Lithuania
Lietuvos_ivarciai                            None
Name: 30, dtype: object



date                 1993-07-03
home_team                Latvia
away_team             Lithuania
home_score                    0
away_score                    0
tourniment           Baltic Cup
city                      Pernu
country                 Estonia
Lietuvos_ivarciai          None
Name: 31, dtype: object



date                 1993-07-04
home_team               Estonia
away_team             Lithuania
home_score                    2
away_score                    1
tourniment           Baltic Cup
city                      Pernu
country                 Estonia
Lietuvos_ivarciai          None
Name: 32, dtype: object



date                                   1993-08-25
home_team                                 Denmark
away_team                               Lithuania
home_score                                      4
away_score                                      0
tourniment           FIFA World Cup qualification
city                                   Copenhagen
country                                   Denmark
Lietuvos_ivarciai                            None
Name: 33, dtype: object



date                                   1993-09-08
home_team                     Republic of Ireland
away_team                               Lithuania
home_score                                      2
away_score                                      0
tourniment           FIFA World Cup qualification
city                                       Dublin
country                       Republic of Ireland
Lietuvos_ivarciai                            None
Name: 34, dtype: object



date                 1994-04-20
home_team             Lithuania
away_team                Israel
home_score                    1
away_score                    1
tourniment             Friendly
city                    Vilnius
country               Lithuania
Lietuvos_ivarciai          None
Name: 35, dtype: object



date                     1994-05-25
home_team            Czech Republic
away_team                 Lithuania
home_score                        5
away_score                        3
tourniment                 Friendly
city                        Ostrava
country              Czech Republic
Lietuvos_ivarciai              None
Name: 36, dtype: object



date                 1994-07-29
home_team             Lithuania
away_team               Estonia
home_score                    3
away_score                    0
tourniment           Baltic Cup
city                    Vilnius
country               Lithuania
Lietuvos_ivarciai          None
Name: 37, dtype: object



date                 1994-07-31
home_team             Lithuania
away_team                Latvia
home_score                    1
away_score                    0
tourniment           Baltic Cup
city                    Vilnius
country               Lithuania
Lietuvos_ivarciai          None
Name: 38, dtype: object



date                 1994-08-17
home_team                Sweden
away_team             Lithuania
home_score                    4
away_score                    2
tourniment             Friendly
city                     �rebro
country                  Sweden
Lietuvos_ivarciai          None
Name: 39, dtype: object



date                              1994-09-07
home_team                            Ukraine
away_team                          Lithuania
home_score                                 0
away_score                                 2
tourniment           UEFA Euro qualification
city                                    Ky�v
country                              Ukraine
Lietuvos_ivarciai                       None
Name: 40, dtype: object



date                              1994-10-09
home_team                            Croatia
away_team                          Lithuania
home_score                                 2
away_score                                 0
tourniment           UEFA Euro qualification
city                                  Zagreb
country                              Croatia
Lietuvos_ivarciai                       None
Name: 41, dtype: object



date                              1994-11-16
home_team                           Slovenia
away_team                          Lithuania
home_score                                 1
away_score                                 2
tourniment           UEFA Euro qualification
city                                 Maribor
country                             Slovenia
Lietuvos_ivarciai                       None
Name: 42, dtype: object



date                              1995-03-15
home_team                             Poland
away_team                          Lithuania
home_score                                 4
away_score                                 1
tourniment                          Friendly
city                 Ostrowiec ?wi?tokrzyski
country                               Poland
Lietuvos_ivarciai                       None
Name: 43, dtype: object



date                              1995-03-29
home_team                          Lithuania
away_team                            Croatia
home_score                                 0
away_score                                 0
tourniment           UEFA Euro qualification
city                                 Vilnius
country                            Lithuania
Lietuvos_ivarciai                       None
Name: 44, dtype: object



date                              1995-04-26
home_team                          Lithuania
away_team                              Italy
home_score                                 0
away_score                                 1
tourniment           UEFA Euro qualification
city                                 Vilnius
country                            Lithuania
Lietuvos_ivarciai                       None
Name: 45, dtype: object



date                 1995-05-17
home_team             Lithuania
away_team                Greece
home_score                    2
away_score                    1
tourniment             Friendly
city                    Vilnius
country               Lithuania
Lietuvos_ivarciai          None
Name: 46, dtype: object



date                 1995-05-20
home_team               Estonia
away_team             Lithuania
home_score                    0
away_score                    7
tourniment           Baltic Cup
city                       Riga
country                  Latvia
Lietuvos_ivarciai          None
Name: 47, dtype: object



date                 1995-05-21
home_team                Latvia
away_team             Lithuania
home_score                    2
away_score                    0
tourniment           Baltic Cup
city                       Riga
country                  Latvia
Lietuvos_ivarciai          None
Name: 48, dtype: object



date                              1995-06-07
home_team                          Lithuania
away_team                           Slovenia
home_score                                 2
away_score                                 1
tourniment           UEFA Euro qualification
city                                 Vilnius
country                            Lithuania
Lietuvos_ivarciai                       None
Name: 49, dtype: object



date                 1995-07-29
home_team             Lithuania
away_team               Belarus
home_score                    1
away_score                    1
tourniment             Friendly
city                    Vilnius
country               Lithuania
Lietuvos_ivarciai          None
Name: 50, dtype: object



date                              1995-08-16
home_team                            Estonia
away_team                          Lithuania
home_score                                 0
away_score                                 1
tourniment           UEFA Euro qualification
city                                 Tallinn
country                              Estonia
Lietuvos_ivarciai                       None
Name: 51, dtype: object



date                              1995-09-06
home_team                          Lithuania
away_team                            Ukraine
home_score                                 1
away_score                                 3
tourniment           UEFA Euro qualification
city                                 Vilnius
country                            Lithuania
Lietuvos_ivarciai                       None
Name: 52, dtype: object



date                              1995-10-11
home_team                          Lithuania